project:
  type: website
  output-dir: docs

website:
  title: "FCE workshop 4_GitWebsite"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: FCE_dashv1.html
        text: Dashboard

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



